### ISSUE TITLE
[NOT PACK RELATED] - ivaTuner Statistics Server and Sodium incompatibility 

### ISSUE THREAD

**Issue by salviija** [Ghostipedia/CosmicFrontiers#12]
**Describe the bug**
The modpack crashes on startup (latest version from github)

**To Reproduce**
1. Launch modpack with 8GB of RAM allocated on Java 17 via Prism launcher

**Expected behavior**
The pack reaches the title screen.

**Screenshots/Crash Reports**
https://mclo.gs/Fqt7Mt4

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Latest from Github

**Comment by salviija** [comment]
Nevermind, of course the warning for using RSS had to be higher up than I scrolled... sigh

**Comment by Ghostipedia** [comment]
I can't resolve this, for future people who find this thread, please either close ivaTuner Statistics Server or remove Embeddium
