### ISSUE TITLE
[ISSUE] - Vanilla Hopper recipe present despite 'gregified' version 

### ISSUE THREAD

**Issue by HelpMySpacebarBroke** [Ghostipedia/CosmicFrontiers#9]
**Describe the bug**
The hopper recipe from vanilla is present at the same time as the "gregified" version (requiring plates, gears, tools)

**Expected behavior**
I assume, either recipe being the only usable one 

**Screenshots/Crash Reports**
![image](https://github.com/Ghostipedia/CosmicFrontiers/assets/85506340/d7f50b12-9210-4b47-b8f0-2904c994db43)
![image](https://github.com/Ghostipedia/CosmicFrontiers/assets/85506340/2eb3ec4f-3774-4541-934b-1185cd9d41ad)

**Desktop:**
 - Pack Version: 0.13-Hotfix

**Comment by srdr2k3** [comment]
Same issue is present with the piston recipe
![image](https://github.com/Ghostipedia/CosmicFrontiers/assets/99605300/88211308-bf26-483f-8742-0fe3fcf7785a)
